### ISSUE TITLE
Restore from k8s backup job

### ISSUE THREAD

**Issue by darioneto** [ysde/grafana-backup-tool#212]
Stupid question, how would I run this on the reverse, to restore backup from the cronjob? 
Or is this only one way? restore manually?

**Comment by declan-fitzpatrick** [comment]
The job can be reversed by adding a `RESTORE=true` block to the config map, or however you are loading the environment variables, the [image checks this for this on start up](https://github.com/ysde/grafana-backup-tool/blob/1e14e490268209d4b2e0f9c21bbaff9d9cc764e1/Dockerfile#L21C12-L21C36). From the [example](https://github.com/ysde/grafana-backup-tool/blob/master/examples/grafana-backup-k8s-cronjob.yaml):

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-backup-tool
  namespace: grafana-backup-tool
data:
  RESTORE: "true" 
  GRAFANA_URL: "http://grafana.grafana.svc.cluster.local:80"
  GRAFANA_TOKEN: "{YOUR_GRAFANA_TOKEN}"
  GRAFANA_ADMIN_ACCOUNT: "backup"
  GRAFANA_ADMIN_PASSWORD: "{YOUR_GRAFANA_ADMIN_PASSWORD}"
  ...
```
